/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface ConditionalTokensInterface extends utils.Interface {
  functions: {
    "balanceOf(address,uint256)": FunctionFragment;
    "redeemPositions(address,bytes32,bytes32,uint256[])": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "payoutNumerators(bytes32,uint256)": FunctionFragment;
    "safeBatchTransferFrom(address,address,uint256[],uint256[],bytes)": FunctionFragment;
    "getPositionId(address,bytes32)": FunctionFragment;
    "balanceOfBatch(address[],uint256[])": FunctionFragment;
    "splitPosition(address,bytes32,bytes32,uint256[],uint256)": FunctionFragment;
    "getConditionId(address,bytes32,uint256)": FunctionFragment;
    "getCollectionId(bytes32,bytes32,uint256)": FunctionFragment;
    "mergePositions(address,bytes32,bytes32,uint256[],uint256)": FunctionFragment;
    "setApprovalForAll(address,bool)": FunctionFragment;
    "reportPayouts(bytes32,uint256[])": FunctionFragment;
    "getOutcomeSlotCount(bytes32)": FunctionFragment;
    "prepareCondition(address,bytes32,uint256)": FunctionFragment;
    "payoutDenominator(bytes32)": FunctionFragment;
    "isApprovedForAll(address,address)": FunctionFragment;
    "safeTransferFrom(address,address,uint256,uint256,bytes)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "balanceOf"
      | "redeemPositions"
      | "supportsInterface"
      | "payoutNumerators"
      | "safeBatchTransferFrom"
      | "getPositionId"
      | "balanceOfBatch"
      | "splitPosition"
      | "getConditionId"
      | "getCollectionId"
      | "mergePositions"
      | "setApprovalForAll"
      | "reportPayouts"
      | "getOutcomeSlotCount"
      | "prepareCondition"
      | "payoutDenominator"
      | "isApprovedForAll"
      | "safeTransferFrom"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "redeemPositions",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "payoutNumerators",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "safeBatchTransferFrom",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getPositionId",
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOfBatch",
    values: [PromiseOrValue<string>[], PromiseOrValue<BigNumberish>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "splitPosition",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getConditionId",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getCollectionId",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "mergePositions",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovalForAll",
    values: [PromiseOrValue<string>, PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "reportPayouts",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BigNumberish>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getOutcomeSlotCount",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "prepareCondition",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "payoutDenominator",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "isApprovedForAll",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;

  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "redeemPositions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "payoutNumerators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeBatchTransferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPositionId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "balanceOfBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "splitPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getConditionId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCollectionId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mergePositions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovalForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reportPayouts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOutcomeSlotCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "prepareCondition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "payoutDenominator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom",
    data: BytesLike
  ): Result;

  events: {
    "ConditionPreparation(bytes32,address,bytes32,uint256)": EventFragment;
    "ConditionResolution(bytes32,address,bytes32,uint256,uint256[])": EventFragment;
    "PositionSplit(address,address,bytes32,bytes32,uint256[],uint256)": EventFragment;
    "PositionsMerge(address,address,bytes32,bytes32,uint256[],uint256)": EventFragment;
    "PayoutRedemption(address,address,bytes32,bytes32,uint256[],uint256)": EventFragment;
    "TransferSingle(address,address,address,uint256,uint256)": EventFragment;
    "TransferBatch(address,address,address,uint256[],uint256[])": EventFragment;
    "ApprovalForAll(address,address,bool)": EventFragment;
    "URI(string,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ConditionPreparation"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ConditionResolution"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PositionSplit"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PositionsMerge"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PayoutRedemption"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TransferSingle"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TransferBatch"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ApprovalForAll"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "URI"): EventFragment;
}

export interface ConditionPreparationEventObject {
  conditionId: string;
  oracle: string;
  questionId: string;
  outcomeSlotCount: BigNumber;
}
export type ConditionPreparationEvent = TypedEvent<
  [string, string, string, BigNumber],
  ConditionPreparationEventObject
>;

export type ConditionPreparationEventFilter =
  TypedEventFilter<ConditionPreparationEvent>;

export interface ConditionResolutionEventObject {
  conditionId: string;
  oracle: string;
  questionId: string;
  outcomeSlotCount: BigNumber;
  payoutNumerators: BigNumber[];
}
export type ConditionResolutionEvent = TypedEvent<
  [string, string, string, BigNumber, BigNumber[]],
  ConditionResolutionEventObject
>;

export type ConditionResolutionEventFilter =
  TypedEventFilter<ConditionResolutionEvent>;

export interface PositionSplitEventObject {
  stakeholder: string;
  collateralToken: string;
  parentCollectionId: string;
  conditionId: string;
  partition: BigNumber[];
  amount: BigNumber;
}
export type PositionSplitEvent = TypedEvent<
  [string, string, string, string, BigNumber[], BigNumber],
  PositionSplitEventObject
>;

export type PositionSplitEventFilter = TypedEventFilter<PositionSplitEvent>;

export interface PositionsMergeEventObject {
  stakeholder: string;
  collateralToken: string;
  parentCollectionId: string;
  conditionId: string;
  partition: BigNumber[];
  amount: BigNumber;
}
export type PositionsMergeEvent = TypedEvent<
  [string, string, string, string, BigNumber[], BigNumber],
  PositionsMergeEventObject
>;

export type PositionsMergeEventFilter = TypedEventFilter<PositionsMergeEvent>;

export interface PayoutRedemptionEventObject {
  redeemer: string;
  collateralToken: string;
  parentCollectionId: string;
  conditionId: string;
  indexSets: BigNumber[];
  payout: BigNumber;
}
export type PayoutRedemptionEvent = TypedEvent<
  [string, string, string, string, BigNumber[], BigNumber],
  PayoutRedemptionEventObject
>;

export type PayoutRedemptionEventFilter =
  TypedEventFilter<PayoutRedemptionEvent>;

export interface TransferSingleEventObject {
  operator: string;
  from: string;
  to: string;
  id: BigNumber;
  value: BigNumber;
}
export type TransferSingleEvent = TypedEvent<
  [string, string, string, BigNumber, BigNumber],
  TransferSingleEventObject
>;

export type TransferSingleEventFilter = TypedEventFilter<TransferSingleEvent>;

export interface TransferBatchEventObject {
  operator: string;
  from: string;
  to: string;
  ids: BigNumber[];
  values: BigNumber[];
}
export type TransferBatchEvent = TypedEvent<
  [string, string, string, BigNumber[], BigNumber[]],
  TransferBatchEventObject
>;

export type TransferBatchEventFilter = TypedEventFilter<TransferBatchEvent>;

export interface ApprovalForAllEventObject {
  owner: string;
  operator: string;
  approved: boolean;
}
export type ApprovalForAllEvent = TypedEvent<
  [string, string, boolean],
  ApprovalForAllEventObject
>;

export type ApprovalForAllEventFilter = TypedEventFilter<ApprovalForAllEvent>;

export interface URIEventObject {
  value: string;
  id: BigNumber;
}
export type URIEvent = TypedEvent<[string, BigNumber], URIEventObject>;

export type URIEventFilter = TypedEventFilter<URIEvent>;

export interface ConditionalTokens extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ConditionalTokensInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    balanceOf(
      owner: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    redeemPositions(
      collateralToken: PromiseOrValue<string>,
      parentCollectionId: PromiseOrValue<BytesLike>,
      conditionId: PromiseOrValue<BytesLike>,
      indexSets: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    payoutNumerators(
      arg0: PromiseOrValue<BytesLike>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    safeBatchTransferFrom(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      ids: PromiseOrValue<BigNumberish>[],
      values: PromiseOrValue<BigNumberish>[],
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getPositionId(
      collateralToken: PromiseOrValue<string>,
      collectionId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    balanceOfBatch(
      owners: PromiseOrValue<string>[],
      ids: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    splitPosition(
      collateralToken: PromiseOrValue<string>,
      parentCollectionId: PromiseOrValue<BytesLike>,
      conditionId: PromiseOrValue<BytesLike>,
      partition: PromiseOrValue<BigNumberish>[],
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getConditionId(
      oracle: PromiseOrValue<string>,
      questionId: PromiseOrValue<BytesLike>,
      outcomeSlotCount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getCollectionId(
      parentCollectionId: PromiseOrValue<BytesLike>,
      conditionId: PromiseOrValue<BytesLike>,
      indexSet: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    mergePositions(
      collateralToken: PromiseOrValue<string>,
      parentCollectionId: PromiseOrValue<BytesLike>,
      conditionId: PromiseOrValue<BytesLike>,
      partition: PromiseOrValue<BigNumberish>[],
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setApprovalForAll(
      operator: PromiseOrValue<string>,
      approved: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    reportPayouts(
      questionId: PromiseOrValue<BytesLike>,
      payouts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getOutcomeSlotCount(
      conditionId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    prepareCondition(
      oracle: PromiseOrValue<string>,
      questionId: PromiseOrValue<BytesLike>,
      outcomeSlotCount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    payoutDenominator(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    isApprovedForAll(
      owner: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    safeTransferFrom(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      value: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  balanceOf(
    owner: PromiseOrValue<string>,
    id: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  redeemPositions(
    collateralToken: PromiseOrValue<string>,
    parentCollectionId: PromiseOrValue<BytesLike>,
    conditionId: PromiseOrValue<BytesLike>,
    indexSets: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  supportsInterface(
    interfaceId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  payoutNumerators(
    arg0: PromiseOrValue<BytesLike>,
    arg1: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  safeBatchTransferFrom(
    from: PromiseOrValue<string>,
    to: PromiseOrValue<string>,
    ids: PromiseOrValue<BigNumberish>[],
    values: PromiseOrValue<BigNumberish>[],
    data: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getPositionId(
    collateralToken: PromiseOrValue<string>,
    collectionId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  balanceOfBatch(
    owners: PromiseOrValue<string>[],
    ids: PromiseOrValue<BigNumberish>[],
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  splitPosition(
    collateralToken: PromiseOrValue<string>,
    parentCollectionId: PromiseOrValue<BytesLike>,
    conditionId: PromiseOrValue<BytesLike>,
    partition: PromiseOrValue<BigNumberish>[],
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getConditionId(
    oracle: PromiseOrValue<string>,
    questionId: PromiseOrValue<BytesLike>,
    outcomeSlotCount: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  getCollectionId(
    parentCollectionId: PromiseOrValue<BytesLike>,
    conditionId: PromiseOrValue<BytesLike>,
    indexSet: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  mergePositions(
    collateralToken: PromiseOrValue<string>,
    parentCollectionId: PromiseOrValue<BytesLike>,
    conditionId: PromiseOrValue<BytesLike>,
    partition: PromiseOrValue<BigNumberish>[],
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setApprovalForAll(
    operator: PromiseOrValue<string>,
    approved: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  reportPayouts(
    questionId: PromiseOrValue<BytesLike>,
    payouts: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getOutcomeSlotCount(
    conditionId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  prepareCondition(
    oracle: PromiseOrValue<string>,
    questionId: PromiseOrValue<BytesLike>,
    outcomeSlotCount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  payoutDenominator(
    arg0: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  isApprovedForAll(
    owner: PromiseOrValue<string>,
    operator: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  safeTransferFrom(
    from: PromiseOrValue<string>,
    to: PromiseOrValue<string>,
    id: PromiseOrValue<BigNumberish>,
    value: PromiseOrValue<BigNumberish>,
    data: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    balanceOf(
      owner: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    redeemPositions(
      collateralToken: PromiseOrValue<string>,
      parentCollectionId: PromiseOrValue<BytesLike>,
      conditionId: PromiseOrValue<BytesLike>,
      indexSets: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    payoutNumerators(
      arg0: PromiseOrValue<BytesLike>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    safeBatchTransferFrom(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      ids: PromiseOrValue<BigNumberish>[],
      values: PromiseOrValue<BigNumberish>[],
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    getPositionId(
      collateralToken: PromiseOrValue<string>,
      collectionId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    balanceOfBatch(
      owners: PromiseOrValue<string>[],
      ids: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    splitPosition(
      collateralToken: PromiseOrValue<string>,
      parentCollectionId: PromiseOrValue<BytesLike>,
      conditionId: PromiseOrValue<BytesLike>,
      partition: PromiseOrValue<BigNumberish>[],
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    getConditionId(
      oracle: PromiseOrValue<string>,
      questionId: PromiseOrValue<BytesLike>,
      outcomeSlotCount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    getCollectionId(
      parentCollectionId: PromiseOrValue<BytesLike>,
      conditionId: PromiseOrValue<BytesLike>,
      indexSet: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    mergePositions(
      collateralToken: PromiseOrValue<string>,
      parentCollectionId: PromiseOrValue<BytesLike>,
      conditionId: PromiseOrValue<BytesLike>,
      partition: PromiseOrValue<BigNumberish>[],
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setApprovalForAll(
      operator: PromiseOrValue<string>,
      approved: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    reportPayouts(
      questionId: PromiseOrValue<BytesLike>,
      payouts: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    getOutcomeSlotCount(
      conditionId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    prepareCondition(
      oracle: PromiseOrValue<string>,
      questionId: PromiseOrValue<BytesLike>,
      outcomeSlotCount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    payoutDenominator(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isApprovedForAll(
      owner: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    safeTransferFrom(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      value: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "ConditionPreparation(bytes32,address,bytes32,uint256)"(
      conditionId?: PromiseOrValue<BytesLike> | null,
      oracle?: PromiseOrValue<string> | null,
      questionId?: PromiseOrValue<BytesLike> | null,
      outcomeSlotCount?: null
    ): ConditionPreparationEventFilter;
    ConditionPreparation(
      conditionId?: PromiseOrValue<BytesLike> | null,
      oracle?: PromiseOrValue<string> | null,
      questionId?: PromiseOrValue<BytesLike> | null,
      outcomeSlotCount?: null
    ): ConditionPreparationEventFilter;

    "ConditionResolution(bytes32,address,bytes32,uint256,uint256[])"(
      conditionId?: PromiseOrValue<BytesLike> | null,
      oracle?: PromiseOrValue<string> | null,
      questionId?: PromiseOrValue<BytesLike> | null,
      outcomeSlotCount?: null,
      payoutNumerators?: null
    ): ConditionResolutionEventFilter;
    ConditionResolution(
      conditionId?: PromiseOrValue<BytesLike> | null,
      oracle?: PromiseOrValue<string> | null,
      questionId?: PromiseOrValue<BytesLike> | null,
      outcomeSlotCount?: null,
      payoutNumerators?: null
    ): ConditionResolutionEventFilter;

    "PositionSplit(address,address,bytes32,bytes32,uint256[],uint256)"(
      stakeholder?: PromiseOrValue<string> | null,
      collateralToken?: null,
      parentCollectionId?: PromiseOrValue<BytesLike> | null,
      conditionId?: PromiseOrValue<BytesLike> | null,
      partition?: null,
      amount?: null
    ): PositionSplitEventFilter;
    PositionSplit(
      stakeholder?: PromiseOrValue<string> | null,
      collateralToken?: null,
      parentCollectionId?: PromiseOrValue<BytesLike> | null,
      conditionId?: PromiseOrValue<BytesLike> | null,
      partition?: null,
      amount?: null
    ): PositionSplitEventFilter;

    "PositionsMerge(address,address,bytes32,bytes32,uint256[],uint256)"(
      stakeholder?: PromiseOrValue<string> | null,
      collateralToken?: null,
      parentCollectionId?: PromiseOrValue<BytesLike> | null,
      conditionId?: PromiseOrValue<BytesLike> | null,
      partition?: null,
      amount?: null
    ): PositionsMergeEventFilter;
    PositionsMerge(
      stakeholder?: PromiseOrValue<string> | null,
      collateralToken?: null,
      parentCollectionId?: PromiseOrValue<BytesLike> | null,
      conditionId?: PromiseOrValue<BytesLike> | null,
      partition?: null,
      amount?: null
    ): PositionsMergeEventFilter;

    "PayoutRedemption(address,address,bytes32,bytes32,uint256[],uint256)"(
      redeemer?: PromiseOrValue<string> | null,
      collateralToken?: PromiseOrValue<string> | null,
      parentCollectionId?: PromiseOrValue<BytesLike> | null,
      conditionId?: null,
      indexSets?: null,
      payout?: null
    ): PayoutRedemptionEventFilter;
    PayoutRedemption(
      redeemer?: PromiseOrValue<string> | null,
      collateralToken?: PromiseOrValue<string> | null,
      parentCollectionId?: PromiseOrValue<BytesLike> | null,
      conditionId?: null,
      indexSets?: null,
      payout?: null
    ): PayoutRedemptionEventFilter;

    "TransferSingle(address,address,address,uint256,uint256)"(
      operator?: PromiseOrValue<string> | null,
      from?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null,
      id?: null,
      value?: null
    ): TransferSingleEventFilter;
    TransferSingle(
      operator?: PromiseOrValue<string> | null,
      from?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null,
      id?: null,
      value?: null
    ): TransferSingleEventFilter;

    "TransferBatch(address,address,address,uint256[],uint256[])"(
      operator?: PromiseOrValue<string> | null,
      from?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null,
      ids?: null,
      values?: null
    ): TransferBatchEventFilter;
    TransferBatch(
      operator?: PromiseOrValue<string> | null,
      from?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null,
      ids?: null,
      values?: null
    ): TransferBatchEventFilter;

    "ApprovalForAll(address,address,bool)"(
      owner?: PromiseOrValue<string> | null,
      operator?: PromiseOrValue<string> | null,
      approved?: null
    ): ApprovalForAllEventFilter;
    ApprovalForAll(
      owner?: PromiseOrValue<string> | null,
      operator?: PromiseOrValue<string> | null,
      approved?: null
    ): ApprovalForAllEventFilter;

    "URI(string,uint256)"(
      value?: null,
      id?: PromiseOrValue<BigNumberish> | null
    ): URIEventFilter;
    URI(value?: null, id?: PromiseOrValue<BigNumberish> | null): URIEventFilter;
  };

  estimateGas: {
    balanceOf(
      owner: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    redeemPositions(
      collateralToken: PromiseOrValue<string>,
      parentCollectionId: PromiseOrValue<BytesLike>,
      conditionId: PromiseOrValue<BytesLike>,
      indexSets: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    payoutNumerators(
      arg0: PromiseOrValue<BytesLike>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    safeBatchTransferFrom(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      ids: PromiseOrValue<BigNumberish>[],
      values: PromiseOrValue<BigNumberish>[],
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getPositionId(
      collateralToken: PromiseOrValue<string>,
      collectionId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    balanceOfBatch(
      owners: PromiseOrValue<string>[],
      ids: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    splitPosition(
      collateralToken: PromiseOrValue<string>,
      parentCollectionId: PromiseOrValue<BytesLike>,
      conditionId: PromiseOrValue<BytesLike>,
      partition: PromiseOrValue<BigNumberish>[],
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getConditionId(
      oracle: PromiseOrValue<string>,
      questionId: PromiseOrValue<BytesLike>,
      outcomeSlotCount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCollectionId(
      parentCollectionId: PromiseOrValue<BytesLike>,
      conditionId: PromiseOrValue<BytesLike>,
      indexSet: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    mergePositions(
      collateralToken: PromiseOrValue<string>,
      parentCollectionId: PromiseOrValue<BytesLike>,
      conditionId: PromiseOrValue<BytesLike>,
      partition: PromiseOrValue<BigNumberish>[],
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setApprovalForAll(
      operator: PromiseOrValue<string>,
      approved: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    reportPayouts(
      questionId: PromiseOrValue<BytesLike>,
      payouts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getOutcomeSlotCount(
      conditionId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    prepareCondition(
      oracle: PromiseOrValue<string>,
      questionId: PromiseOrValue<BytesLike>,
      outcomeSlotCount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    payoutDenominator(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isApprovedForAll(
      owner: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    safeTransferFrom(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      value: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    balanceOf(
      owner: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    redeemPositions(
      collateralToken: PromiseOrValue<string>,
      parentCollectionId: PromiseOrValue<BytesLike>,
      conditionId: PromiseOrValue<BytesLike>,
      indexSets: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    payoutNumerators(
      arg0: PromiseOrValue<BytesLike>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    safeBatchTransferFrom(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      ids: PromiseOrValue<BigNumberish>[],
      values: PromiseOrValue<BigNumberish>[],
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getPositionId(
      collateralToken: PromiseOrValue<string>,
      collectionId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    balanceOfBatch(
      owners: PromiseOrValue<string>[],
      ids: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    splitPosition(
      collateralToken: PromiseOrValue<string>,
      parentCollectionId: PromiseOrValue<BytesLike>,
      conditionId: PromiseOrValue<BytesLike>,
      partition: PromiseOrValue<BigNumberish>[],
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getConditionId(
      oracle: PromiseOrValue<string>,
      questionId: PromiseOrValue<BytesLike>,
      outcomeSlotCount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCollectionId(
      parentCollectionId: PromiseOrValue<BytesLike>,
      conditionId: PromiseOrValue<BytesLike>,
      indexSet: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    mergePositions(
      collateralToken: PromiseOrValue<string>,
      parentCollectionId: PromiseOrValue<BytesLike>,
      conditionId: PromiseOrValue<BytesLike>,
      partition: PromiseOrValue<BigNumberish>[],
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setApprovalForAll(
      operator: PromiseOrValue<string>,
      approved: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    reportPayouts(
      questionId: PromiseOrValue<BytesLike>,
      payouts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getOutcomeSlotCount(
      conditionId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    prepareCondition(
      oracle: PromiseOrValue<string>,
      questionId: PromiseOrValue<BytesLike>,
      outcomeSlotCount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    payoutDenominator(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isApprovedForAll(
      owner: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    safeTransferFrom(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      value: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
