/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface ConstructedCloneFactoryInterface extends utils.Interface {
  functions: {
    "cloneConstructor(bytes)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "cloneConstructor"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "cloneConstructor",
    values: [PromiseOrValue<BytesLike>]
  ): string;

  decodeFunctionResult(
    functionFragment: "cloneConstructor",
    data: BytesLike
  ): Result;

  events: {
    "CloneCreated(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CloneCreated"): EventFragment;
}

export interface CloneCreatedEventObject {
  target: string;
  clone: string;
}
export type CloneCreatedEvent = TypedEvent<
  [string, string],
  CloneCreatedEventObject
>;

export type CloneCreatedEventFilter = TypedEventFilter<CloneCreatedEvent>;

export interface ConstructedCloneFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ConstructedCloneFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    cloneConstructor(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  cloneConstructor(
    arg0: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    cloneConstructor(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "CloneCreated(address,address)"(
      target?: PromiseOrValue<string> | null,
      clone?: null
    ): CloneCreatedEventFilter;
    CloneCreated(
      target?: PromiseOrValue<string> | null,
      clone?: null
    ): CloneCreatedEventFilter;
  };

  estimateGas: {
    cloneConstructor(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    cloneConstructor(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
