/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ConstructedCloneFactory,
  ConstructedCloneFactoryInterface,
} from "../ConstructedCloneFactory";

const _abi = [
  {
    constant: false,
    inputs: [
      {
        name: "",
        type: "bytes",
      },
    ],
    name: "cloneConstructor",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        name: "target",
        type: "address",
      },
      {
        indexed: false,
        name: "clone",
        type: "address",
      },
    ],
    name: "CloneCreated",
    type: "event",
  },
];

export class ConstructedCloneFactory__factory {
  static readonly abi = _abi;
  static createInterface(): ConstructedCloneFactoryInterface {
    return new utils.Interface(_abi) as ConstructedCloneFactoryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ConstructedCloneFactory {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ConstructedCloneFactory;
  }
}
